parameters:
  app.name: 'Bacula-Web'
  # x-release-please-start-version
  app.version: '10.0.0'
  # x-release-please-end

  #
  # Core app parameters
  #
  app.min_php_version: '7.4'

  #
  # General settings
  # Below parameters should be editable by end-user through a nice web ui (form)
  #
  app.datetime_format: '%env(string:APP_DATETIME_FORMAT)%'
  app.datetime_format_short: '%env(string:APP_DATETIME_FORMAT_SHORT)%'
  app.show_inactive_clients: '%env(bool:APP_SHOW_INACTIVE_CLIENTS)%'
  app.hide_empty_pools: '%env(bool:APP_HIDE_EMPTY_POOLS)%'
  app.language: '%env(string:APP_LANGUAGE)%'
  app.rows_per_page: '%env(int:APP_ROWS_PER_PAGE)%'

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true
    autoconfigure: true

  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  App\:
    resource: '../application/'
    exclude:
      - '../application/config/'